/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DrugJpaController;
import Controller.TreatmentJpaController;
import Model.Drug;
import Model.Person;
import Model.Treatment;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import view.EntityListModel;

/**
 *
 * @author dardar2000
 */
public class AddTreatmentWindow extends javax.swing.JFrame {
    private final EntityManagerFactory emfac = Persistence.createEntityManagerFactory("patientfollowup");
    private final DrugJpaController drugCtrl = new DrugJpaController(emfac);
    private final TreatmentJpaController treatmentCtrl = new TreatmentJpaController(emfac);
    private static final Logger LOGGER = LogManager.getLogger(AddTreatmentWindow.class.getName());
    Drug selected = null;
    /**
     * Creates new form AddTreatmentWindow
     */
    public AddTreatmentWindow() {
        initComponents();
    }
    
    public AddTreatmentWindow(Person person) {
        System.out.println("test2");
        initComponents();
        System.out.println("test3");
        patientTextField.setText(person.getFirstname() + person.getLastname());
        System.out.println("test4");
        refreshDrugList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        treatmentNameTextField = new javax.swing.JTextField();
        patientTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugList = new javax.swing.JList<>();
        createTreatmentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom du traitement : ");

        jLabel2.setText("Patient concerné");

        jLabel3.setText("Drug :");

        treatmentNameTextField.setText("jTextField1");
        treatmentNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentNameTextFieldActionPerformed(evt);
            }
        });

        patientTextField.setText("jTextField1");
        patientTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientTextFieldActionPerformed(evt);
            }
        });

        drugList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        drugList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drugListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(drugList);

        createTreatmentButton.setText("Créer le traitement");
        createTreatmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTreatmentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(treatmentNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addComponent(patientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createTreatmentButton)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(treatmentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createTreatmentButton)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void treatmentNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treatmentNameTextFieldActionPerformed

    private void patientTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientTextFieldActionPerformed

    private void drugListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drugListMouseClicked

            EntityListModel<Drug> model = (EntityListModel) drugList.getModel();
            selected = model.getList().get(drugList.getSelectedIndex());
          
    }//GEN-LAST:event_drugListMouseClicked

    private void createTreatmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTreatmentButtonActionPerformed
        Treatment treatment = new Treatment();
        List<Drug> drugList = new ArrayList<>();
        
        System.out.println(selected.getIddrug());
        //drugList.add(selected);
        //treatment.setDrugtList(drugList);
        treatment.setIddrug(selected.getIddrug());
        treatment.setName(treatmentNameTextField.getText());
        treatment.setSideeffect("à remplir par le patient");
        
        treatmentCtrl.create(treatment);
    }//GEN-LAST:event_createTreatmentButtonActionPerformed

    private void refreshDrugList() {
        //J-list are based on model --> entitylistmodel allow to have a list of an object we want (here patient)
        //Patient patient = patientCtrl.findByIdperson(person); //Je prends le patient lié à la personne connectée
        //System.out.println(patient.toString()); //test
        List drug = drugCtrl.findDrugEntities(); //Je prends la liste de traitement de ce patient 
        System.out.println("test");
        EntityListModel<Drug> model = new EntityListModel(drug);
        System.out.println("test2");
        drugList.setModel(model);
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTreatmentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTreatmentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTreatmentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTreatmentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTreatmentWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createTreatmentButton;
    private javax.swing.JList<String> drugList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientTextField;
    private javax.swing.JTextField treatmentNameTextField;
    // End of variables declaration//GEN-END:variables
}
