/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DoctorJpaController;
import Controller.PatientJpaController;
import Controller.PersonJpaController;
import Model.Patient;
import Model.Person;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import view.EntityListModel;

/**
 *
 * @author sarah
 */
public class DoctorWindow extends javax.swing.JFrame {
    private Person person;
    
    private final EntityManagerFactory emfac = Persistence.createEntityManagerFactory("patientfollowup"); 
    PersonJpaController personCtrl = new PersonJpaController(emfac);
    private final PatientJpaController patientCtrl = new PatientJpaController(emfac);
    private final DoctorJpaController doctorCtrl = new DoctorJpaController(emfac);
    //PatientJpaController patientCtrl = new PatientJpaController(emfac);

    /**
     * Creates new form DoctorWindow
     */
    public DoctorWindow() {
        initComponents();
    }
    
    public DoctorWindow(Person p) {
        initComponents();
        welcomeDoctorLabel.setVisible(true);
        welcomeDoctorLabel.setText("Welcome doctor " + p.getLastname());
        person = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeDoctorLabel = new javax.swing.JLabel();
        refreshPatientButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPatient = new javax.swing.JList<>();
        selectPatientLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeDoctorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeDoctorLabel.setText("Welcome Doctor !");

        refreshPatientButton.setText("Refresh");
        refreshPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshPatientButtonActionPerformed(evt);
            }
        });

        listPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPatientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listPatient);

        selectPatientLabel.setText("Select a patient :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(welcomeDoctorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(selectPatientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshPatientButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeDoctorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectPatientLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPatientMouseClicked
        if (evt.getClickCount() == 2){
            System.out.println("double click");
            EntityListModel<Person> model = (EntityListModel) listPatient.getModel();
            Person selected = model.getList().get(listPatient.getSelectedIndex());
            // changer le type de selected en person au lieu de patient
            PatientWindow patientWindow = new PatientWindow(selected);
            patientWindow.setVisible(true);
            //ouvrir la treatmentwindow du traitment selected
        }
    }//GEN-LAST:event_listPatientMouseClicked

    private void refreshPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshPatientButtonActionPerformed
        refreshPatientList();    }//GEN-LAST:event_refreshPatientButtonActionPerformed

    private void refreshPatientList() {
        
        List patient = patientCtrl.findPatientEntities();
        EntityListModel<Patient> model = new EntityListModel(patient);
        
        listPatient.setModel(model);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listPatient;
    private javax.swing.JButton refreshPatientButton;
    private javax.swing.JLabel selectPatientLabel;
    private javax.swing.JLabel welcomeDoctorLabel;
    // End of variables declaration//GEN-END:variables

}
