/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.PersonJpaController;
import Controller.TreatmentJpaController;
import Model.Person;
import Model.Treatment;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import view.EntityListModel;

/**
 *
 * @author dardar2000
 */
public class PatientWindow extends javax.swing.JFrame {
private final EntityManagerFactory emfac = Persistence.createEntityManagerFactory("patientfollowup");
PersonJpaController personCtrl = new PersonJpaController(emfac);
private final TreatmentJpaController treatmentCtrl = new TreatmentJpaController(emfac);
Person person; 

    /**
     * Creates new form PatientWindow
     */
    public PatientWindow() {
        initComponents();
    }
    
      public PatientWindow(Person p) {
          initComponents();
       patientNameLabel.setVisible(true);
       patientNameLabel.setText(p.getFirstname() + " " + p.getLastname());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treatmentList = new javax.swing.JList<>();
        refreshTreatmentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        patientNameLabel.setText("Patient Name");

        jLabel1.setText("Vos traitements :");

        treatmentList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Traitement 1", "Traitement 2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        treatmentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treatmentListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(treatmentList);

        refreshTreatmentButton.setText("Refresh");
        refreshTreatmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTreatmentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(refreshTreatmentButton)
                        .addGap(18, 18, 18)
                        .addComponent(patientNameLabel)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientNameLabel)
                    .addComponent(refreshTreatmentButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void treatmentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treatmentListMouseClicked
        if (evt.getClickCount()==2){
            EntityListModel<Treatment> model = (EntityListModel) treatmentList.getModel();
            Treatment selected = model.getList().get(treatmentList.getSelectedIndex());
            //ouvrir la treatmentwindow du traitment selected
        }
    }//GEN-LAST:event_treatmentListMouseClicked

    private void refreshTreatmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTreatmentButtonActionPerformed
        refreshTreatmentList();
    }//GEN-LAST:event_refreshTreatmentButtonActionPerformed
    private void refreshTreatmentList(){
        //J-list are based on model --> entitylistmodel allow to have a list of an object we want (here patient)
        List treatment = treatmentCtrl.findTreatmentEntities();
        EntityListModel<Treatment> model = new EntityListModel(treatment);
        
        treatmentList.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JButton refreshTreatmentButton;
    private javax.swing.JList<String> treatmentList;
    // End of variables declaration//GEN-END:variables
}
